feat: Reduced length of headRef to 60 characters
mailergroup/env-action pull request #12
Opened 2023-04-04 15:50 UTC by igorhrcek

https://github.com/mailerlite/sre/issues/2259

2023-04-04 15:54 UTC, robgordon89 requested changes

2023-04-04 15:54 UTC, robgordon89 commented on index.test.js
> +});
can you add a test that actully checks the response also 👍

2023-04-04 16:06 UTC, igorhrcek commented on index.test.js
> +});
Added

2023-04-05 07:01 UTC, robgordon89 approved these changes

2023-04-05 11:42 UTC, merged